### ISSUE TITLE
transfer ephys sessions with bulk user input

### ISSUE THREAD

**Issue by nbonacchi** [int-brain-lab/iblscripts#25] opened 2020-01-13 11:12 UTC

**Comment by anne-urai** [comment] 2020-08-12 19:28
Related: https://github.com/int-brain-lab/iblrig/issues/302

**Comment by rossant** [comment] 2020-09-14 11:44
Duplicate of https://github.com/int-brain-lab/iblenv/issues/10

**Closed by rossant** 2020-09-14 11:44 UTC
